---
kind: pipeline
name: bahc_ohana_ui

platform:
  os: linux
  arch: amd64

services:
  - name: database
    image: mdillon/postgis:10
    environment:
      POSTGRES_DB: ohana_ui_test
      POSTGRES_USER: postgres
    ports:
        - 5432

steps:
  - name: tests
    image: ruby:2.5.3
    environment:
      RAILS_ENV: test
      OHANA_API_ENDPOINT: http://ohana-api-test.herokuapp.com/api
    commands:
      - apt-get update && apt-get install apt-transport-https
      - curl -sL https://deb.nodesource.com/setup_13.x | bash -
      - apt-get update && apt-get install -y nodejs
      - export PHANTOMJS_SHA256=86dd9a4bf4aee45f1a84c9f61cf1947c1d6dce9b9e8d2a907105da7852460d2f
      - mkdir /usr/local/phantomjs \
        && curl -o phantomjs.tar.bz2 -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
        && echo "$PHANTOMJS_SHA256 *phantomjs.tar.bz2" | sha256sum -c - \
        && tar -xjf phantomjs.tar.bz2 -C /usr/local/phantomjs --strip-components=1 \
        && rm phantomjs.tar.bz2
      - ln -s ../phantomjs/bin/phantomjs /usr/local/bin/
      - gem install bundler --conservative
      - bundle check || bundle install --jobs 20 --retry 5
      - cp config/drone.database.yml config/database.yml
      - sleep 15
      - RAILS_ENV=test bundle exec rake db:create db:schema:load
      - bundle exec rspec spec

trigger:
  event:
    - pull_request
